#!/bin/bash
cp ~/bin/dwmstat.sh .
cp ~/bin/xlight.sh .
cp ~/.bashrc .
cp ~/.xinitrc .
cp ~/.vimrc .
cp ~/.config/dunst/dunstrc .
cp ~/.config/picom.conf .
cp ~/Documents/prog/suckless/st/config.h ./st.config.h
cp ~/Documents/prog/suckless/dwm/config.h ./dwm.config.h
